ID analyzer
real-social-media/backend pull request #211
Opened 2021-05-18 13:35 UTC by zkhin

https://real-social.atlassian.net/browse/BE-138

2021-05-18 15:44 UTC, mfogel reviewed
Nice work. I made a few targeted comments but there is a bigger structural pattern that you may or may not have seen before.

Typically 'clients' are per-service. So in this case there might be a `JumioClient` and an `IdAnalyzerClient`. You can see this in the design of the AWS SDK. You wouldn't typically combine two services into one client.

If I were coding this up, I would probably:
- make two separate client classes, one for each service. They would present very similar public apis to the rest of the code base. As similar as possible.
- I would add unit tests for each of the clients! I would use `requests-mock` to mock the request-response cycle of each service. Here's an example of how to do that: https://github.com/real-social-media/backend/blob/v2021-05-10/real-main/app_tests/clients/test_post_verification.py
- I would add a config variable, probably defined in the `environment` section of  `serverless.yml`, that allows us to choose between
  - enabling jumio: `IDVERIFICATION_SERVICE: jumio`
  - enabling idverify: `IDVERIFICATION_SERVICE: idverify`
  - explicitly disabling both: `IDVERIFICATION_SERVICE: disabled`

2021-05-18 15:44 UTC, mfogel commented on real-main/app/clients/id_verification.py
> +            return
I think this check could hide errors if the entries in the SecretsManager are misconfigured? Better to fail early and loudly....

If you're looking for an easy way to disable the service, I would do that either with another property in the secrets manager json or possibly with a special api key of something like `DISABLED`

2021-05-19 18:21 UTC, zkhin commented on real-main/app/clients/id_verification.py
> +        if 'error' in result:
Yes, it always returns 200 response with error code.

```
code: 200
{
    "error": {
        "message": "Document not recognized",
        "code": 9
    },
    "executionTime": 1.1604459285736084,
    "responseID": "2db13335fed442fc15aa0c123e69f821"
}
```

2021-05-19 20:12 UTC, mfogel requested changes
Nice work @zkhin , let me know if you have questions/thoughts

2021-05-19 20:12 UTC, mfogel commented on real-main/app/handlers/appsync/handlers.py
> +        caller_user.verify_id_document_with_id_analyzer(frontside_image=frontside_image)
So I don't want to add to much to this task, but if I were coding this up, I would try to do the actual verification with the external id verification service asynchronously using dynamo streams. So that would involve writing some changes to dynamo to record the frontend's ID verification request, then actually doing the call to the IDVerification service from the dynamo stream handler.

This is partly for performance, but more so for reliability and error isolation. Like if IdVerify goes down, and we're accessing it synchronously, then all of the sudden we're sending server errors to the frontend, which it should be able to handle but probably isn't a scenario they test everyday...

Feel free to ignore this comment if you'd rather move on to the next task 🙂

2021-05-19 20:53 UTC, zkhin commented on real-main/app/handlers/appsync/handlers.py
> +        caller_user.verify_id_document_with_id_analyzer(frontside_image=frontside_image)
That makes sense and it will be better to use a dynamo stream handler.
If you don't mind, I would like to create a new task for this refactoring and will come back again later.

2021-05-20 00:20 UTC, mfogel approved these changes

2021-05-20 00:21 UTC, mfogel commented on real-main/app/clients/id_verification.py
> +        if 'error' in result:
👍

2021-05-20 00:34 UTC, merged