New user fields location match genders etc
real-social-media/backend pull request #67
Opened 2020-09-18 14:27 UTC by zkhin

Fixes: https://trello.com/c/NSNZv4VS/14-new-user-fields-currentlocation-matchgenders-matchagerange-matchlocationradius

2020-09-19 12:45 UTC, mfogel requested changes
Nice work! Please address these comments when you have time.

Please also double-check to make sure all the existing integration tests pass... I suspect they don't? Specifically, I think this one probably fails? https://github.com/real-social-media/backend/blob/v2020-09-15/integration-testing/tests/block/reads.test.js#L23. I haven't tested it directly myself. There may be others that fail as well, not sure.

2020-09-19 12:45 UTC, mfogel commented on real-main/schema.graphql
> +    matchLocationRadius: Int
```suggestion
    matchLocationRadius: Int,
```

I think the lint rules are ok with trailing commas in situations like this... let's use one here if possible.

2020-09-19 12:45 UTC, mfogel commented on real-main/app/handlers/appsync/handlers.py
> +
The code/logic here to do all this validation looks good, but the problem is that when it's in the handler function it is hard to unit test. So I think we should move it, and unit test it. (I realize there are integration tests for this, that's great, but we need unit tests also whenever possible 😊 )

Two options come to mind. I'm ok with either of these, though I think the second one is more the 'right' answer...

1. Move the logic to within `User.update_details()`. `User.updateDetails()` would raise a `UserException` (or a subclass of `UserException`, which would be caught in the handler function, which would then raise a `ClientException`. Unit tests would go in `app_tests/models/user/test_model.py`

1. Make a new file `app/handlers/appsync/validation.py` that has functions like `def validate_match_location_radius(value)`, `def validate_age_range(value)` etc. Those functions could throw a `ClientException` directly. They would of course be called from this file. You would also need a new file for unit tests for these functions: `app_tests/handlers/appsync/test_validation.py`

2020-09-19 12:45 UTC, mfogel commented on integration-testing/schema/queries.js
> +      matchLocationRadius
Instead of adding this stanza here, could you add it to `integration-testing/schema/fragments.js` in the `simpleUserFields` fragment? Then it will also show up in the other queries, not just in `Query.self`

2020-09-19 12:45 UTC, mfogel commented on integration-testing/tests/users/properties.test.js
> +})
We need integration test(s) to verify that when a user tries to read these fields on a different user, they just get `null` for each field. These fields should be private: I can only read my own values, I can't read anybody else's.

To get that to work, I think you're going to need to add resolvers and mapping templates for each of these fields using `NoneDataSource`. `User.email` looks like a good example to follow:
- https://github.com/real-social-media/backend/blob/v2020-09-15/real-main/mapping-templates/User.email.request.vtl
- https://github.com/real-social-media/backend/blob/v2020-09-15/real-main/serverless/mapping-templates/user.yml#L86-L89

2020-09-21 17:19 UTC, mfogel requested changes

2020-09-21 17:19 UTC, mfogel commented on integration-testing/tests/users/properties.test.js
> +  })
This is good, except it does not pass. The test is now correct, but the backend implementation is not.

To get this to work, I think you're going to need to add resolvers and mapping templates for each of these fields using NoneDataSource. User.email looks like a good example to follow:

- https://github.com/real-social-media/backend/blob/v2020-09-15/real-main/mapping-templates/User.email.request.vtl
- https://github.com/real-social-media/backend/blob/v2020-09-15/real-main/serverless/mapping-templates/user.yml#L86-L89

2020-09-21 17:25 UTC, zkhin commented on integration-testing/tests/users/properties.test.js
> +  })
Oh, my bad. I committed files in the `integration-testing` directory so the new vtl files are not pushed yet...

2020-09-22 13:24 UTC, mfogel requested changes

2020-09-22 13:24 UTC, mfogel commented on real-main/app/handlers/appsync/handlers.py
> +        current_location = {"latitude": latitude, "longitude": longitude, "accuracy": accuracy}
A few thoughts on this:

- Since using `Decimal` is essentially a dynamodb requirement, I think we should probably put this conversion 'closer' to dynamo. Probably in the method `set_user_details()` of `real-main/app/models/user/dynamo/base.py`
- if `accuracy` isn't set by the client, let's leave it not set in dynamo (don't fill in a zero)
- in the interest of 'fail early and often' I would do `current_location['latitude']`, not `current_location.get('latitude')`
- to convert a float to a decimal, I think this is a better formulation:

```py
from decimal import BasicContext
my_float = 6/7
my_decimal = BasicContext.create_decimal(my_float).normalize()
```

I'm going to go through other places in this project where we use `Decimal` and change them to initialize decimals in this way (will do that in a separate commit, not part of this PR)

2020-09-22 13:24 UTC, mfogel commented on real-main/mapping-templates/User.currentLocation.request.vtl
> +## email is private to the user themselves
```suggestion
## private to the user themselves
```

This suggestion applies to the other mapping templates in this PR as well.

2020-09-22 13:24 UTC, mfogel commented on real-main/mapping-templates/User.currentLocation.request.vtl
> +  #return ()
```suggestion
  #return
```

Simpler way to write the same thing I discovered a few months ago. This suggestion applies to the other mapping templates in this PR as well.

2020-09-22 14:45 UTC, mfogel reviewed
I haven't reviewed the unit tests in detail yet, I will later today

2020-09-22 14:45 UTC, mfogel commented on real-main/app/models/user/dynamo/base.py
> +            current_location = {"latitude": latitude, "longitude": longitude, "accuracy": accuracy}
This is better - but this will still sometimes try to write null/None into dynamo...

```suggestion
            current_location = {"latitude": latitude, "longitude": longitude}
            if 'accuracy' in current_location:
                current_location['accuracy'] = BasicContext.create_decimal(current_location['accuracy']).normalize()            
```

Please make sure the unit tests for this function check the situations where
- accuracy is not set
- accuracy is set

2020-09-22 14:50 UTC, mfogel commented on real-main/app/models/user/dynamo/base.py
> +            current_location = {"latitude": latitude, "longitude": longitude, "accuracy": accuracy}
```suggestion
        for key in ('latitude', 'longitude'):
            current_location[key] = BasicContext.create_decimal(current_location[key]).normalize()
```

We actually don't need to apply the conversion to `Decimal` to accuracy because it is an integer, not a float.

2020-09-22 14:56 UTC, mfogel commented on real-main/app/models/user/dynamo/base.py
> +            current_location = {"latitude": latitude, "longitude": longitude, "accuracy": accuracy}
You may need to check and handle the situation where `accuracy` is in `current_location`, but has value `None`. I'm not sure if this is needed - it depends on how appsync/graphql handles the situation where `accuracy`:
  - is just missing from the GQL type
  - is in the GQL type with value `null`

So you might need to add something like this:

```py
if current_location.get('accuracy') is None:
  current_location.pop('accuracy', None)
```

2020-09-22 17:56 UTC, mfogel commented on real-main/app_tests/handlers/appsync/test_validation.py
> +def test_validate_current_location():
Values I would make sure to test here:

- latitude:
  - -90
  - 90
  - 0
  - -90.1
  - 90.1
- longitude
  - -180
  - 180
  - 0
  - -180.1
  - 180.1
- accuracy
  - 0
  - some integer greater than 0... say 42
  - None
  - not present

2020-09-22 17:56 UTC, mfogel commented on real-main/app_tests/models/user/test_dynamo.py
> +    assert resp['currentLocation'].get('accuracy') is None
```suggestion
    assert 'accuracy' not in resp['currentLocation']
```

This suggestion is a slightly stricter assertion - it should ensure we aren't storing a null in dynamo

2020-09-22 17:56 UTC, mfogel commented on real-main/app_tests/models/user/test_dynamo.py
> +    match_location_radius = Decimal('15')
I think all these should be floats or ints, not Decimals anymore

2020-09-23 12:09 UTC, mfogel reviewed
Minor fixes to get the integration tests to pass. I think after these changes it will be ready to merge in.

2020-09-23 12:09 UTC, mfogel commented on integration-testing/tests/users/properties.test.js
> +  ).rejects.toThrow(/ClientError: MatchLocationRadius should be greater than or equal to 15/)
```suggestion
  ).rejects.toThrow(/ClientError: matchLocationRadius should be greater than or equal to 15/)
```

2020-09-23 12:09 UTC, mfogel commented on integration-testing/tests/users/properties.test.js
> +  ).rejects.toThrow('GraphQL error: ClientError: Latitude should be in [-90, 90]')
```suggestion
  ).rejects.toThrow(/ClientError: latitude should be in \[-90, 90\]/)
```

2020-09-23 12:09 UTC, mfogel commented on integration-testing/tests/users/properties.test.js
> +  ).rejects.toThrow('GraphQL error: ClientError: Longitude should be in [-180, 180]')
```suggestion
  ).rejects.toThrow(/ClientError: longitude should be in \[-180, 180\]/)
```

2020-09-23 12:09 UTC, mfogel commented on integration-testing/tests/users/properties.test.js
> +  ).rejects.toThrow(/ClientError: Accuracy should be greater than or equal to zero/)
```suggestion
  ).rejects.toThrow(/ClientError: accuracy should be greater than or equal to zero/)
```

2020-09-23 13:55 UTC, merged