Bug:Steal user email/phoneNumber exception
real-social-media/backend pull request #71
Opened 2020-09-30 17:37 UTC by zkhin

Fixes: https://trello.com/c/nKpMIivz/24-user-attempting-to-steal-an-email-address-from-another-user-results-in-errors-and-inconsistent-backend-state

2020-09-30 18:21 UTC, mfogel requested changes
Nice job figuring this out in an email/phone agnostic way. And also thanks for adding an integration test!

Let me know if you thoughts/questions on these comments, cheers.

2020-09-30 18:21 UTC, mfogel commented on real-main/app/models/user/model.py
> +        attribute_dynamo = UserContactAttributeDynamo(self.dynamo, f'user{names["dynamo"].title()}')
Nice job figuring this out. There's some improvements we can do.

Rather than initiating  a new copy of the `UserContactAttributeDynamo` library each time this method is called, on each `User` model instance, it would be better if we re-use the one that the `UserManager` already has. All the dynamo libraries (in fact all the python code except the models themselves - in `model.py`) are designed to be state-less, hence they should be shared like this as much as possible. Here's what I would do.

- add two new kwargs to `User.__init__()`: `email_dynamo` and `phone_number_dynamo`. Save those as `self.email_dynamo` and `self.phone_number_dynamo`
- make changes to `UserManager.init_user()` so that `UserManager.email_dyanmo` and `UserManager.phone_number_dynamo` are both based in to `User.__init__()`
- use `getattr()` here to select the right library: either `self.email_dynamo` or `self.phone_number_dynamo`

2020-09-30 18:21 UTC, mfogel commented on integration-testing/tests/users/steal-user-email-phone.test.js
> +  loginCache.addCleanLogin(await cognito.getAppSyncLogin(theirPhone))
Two thoughts here:

- `+15105551000` is already in use by another integration test. We have to use unique phone numbers in each test file, so that they can be run in parallel. So I would change this to some other valid phone number that is not yet in use by our integration tests.
- I wouldn't bother to declare `ourPhone` and `theirPhone` here... I generally stay away from declaring variables just as documentation unless it's something seriously complicated. So to me, doing `loginCache.addCleanLogin(await cognito.getAppSyncLogin('+1...'))` would be better.

2020-09-30 18:21 UTC, mfogel commented on integration-testing/tests/users/steal-user-email-phone.test.js
> +afterEach(async () => {})
```suggestion
```

No need for the empty `afterEach()`, can be removed.

2020-09-30 18:21 UTC, mfogel commented on integration-testing/tests/users/steal-user-email-phone.test.js
> +`
I would put these in `schema/mutations.js`

2020-09-30 18:21 UTC, mfogel commented on integration-testing/tests/users/steal-user-email-phone.test.js
> +  })
```suggestion

  const ourPhoneNumber = await ourClient.query({query: queries.self}).then(({data: {self: user}}) => user.phoneNumber)
```

2020-09-30 19:00 UTC, zkhin commented on integration-testing/tests/users/steal-user-email-phone.test.js
> +  loginCache.addCleanLogin(await cognito.getAppSyncLogin(theirPhone))
I used this code instead of above but I am getting the `null` value for the phoneNumber
```
loginCache.addCleanLogin(await cognito.getAppSyncLogin('+15105551000'))
loginCache.addCleanLogin(await cognito.getAppSyncLogin('+15105551111'))
```
But if I use old code, it works fine... weird...

2020-09-30 19:16 UTC, mfogel commented on integration-testing/tests/users/steal-user-email-phone.test.js
> +  loginCache.addCleanLogin(await cognito.getAppSyncLogin(theirPhone))
Yeah, what's probably going on is there is already a user in your dynamo & cognito with that phone number. The users in the integration test suite are linked to the line number of the file that creates them. So since the line numbers change with this change, then the test is unable to create another user with that same phone number (since one already exists).

We avoid this with emails by generating valid emails on-the-fly. Can't do that with phone numbers... at least I don't know how. It's not as simple as picking a random number.

What you can do to fix your test env:

- run the script `integration-testing/clean/clear-dynamodb-table`
- see if that fixes it
- if not, run that script again and then also run `integration-testing/clean/clear-user-pool` (takes a few minutes to run)

2020-09-30 19:33 UTC, zkhin commented on integration-testing/tests/users/steal-user-email-phone.test.js
> +  loginCache.addCleanLogin(await cognito.getAppSyncLogin(theirPhone))
Stucked while running `cleaer-user-pool` script
![image](https://user-images.githubusercontent.com/4212008/94731099-950cd500-03a7-11eb-848b-ac209f2047ae.png)

2020-10-01 15:11 UTC, mfogel commented on real-main/app/models/user/model.py
> +        if self.email_dynamo.get(attribute_value) or self.phone_number_dynamo.get(attribute_value):
This works but as I imagine you know, it will query email addresses for a phone number, which is a waste of a query. Here's one way to avoid that useless query.

First, change the definition of `CONTACT_ATTRIBUTE_NAMES` like so:

```py
CONTACT_ATTRIBUTE_NAMES = {
    'email': {
        'short': 'email',
        'cognito': 'email',
        'dynamo_attr': 'email',
        'dynamo_client': 'email_dynamo',
    },
    'phone': {
        'short': 'phone',
        'cognito': 'phone_number',
        'dynamo_attr': 'phoneNumber',
        'dynamo_client': 'phone_number_dynamo',
    },
}
```

then this part here becomes

```suggestion
        contact_attr_dyamo = getattr(self, names[attribute_name])
        if contact_attr_dynamo.get(attribute_value):
```

Also, existing code of `names['dynamo']` will need to be changed to `names['dynamo_attr']`

2020-10-01 16:38 UTC, merged