Change findUsers to findContacts
real-social-media/backend pull request #72
Opened 2020-10-01 20:03 UTC by zkhin

fixes: https://trello.com/c/yAmly0Er/25-change-queryfindusers-into-queryfindcontacts

2020-10-02 15:27 UTC, mfogel requested changes
Some minor performance improvements, python niceties

2020-10-02 15:27 UTC, mfogel commented on real-main/app/models/user/manager.py
> +            user_id = user_ids_mapped_attrs[attr]
```suggestion
        for attr, user_id in user_ids_mapped_attrs.items():
```

2020-10-02 15:27 UTC, mfogel commented on real-main/app/models/user/manager.py
> +        contact_ids_mapped_attrs = {**email_contacts, **phone_contacts}
Naming suggestion, take it or leave it as you like. This is personal preference, but I would find this more clear with variable names like

```
email_to_user_id = ...
phone_to_user_id = ...
conatct_attr_to_user_id = ...
```
etc

2020-10-02 15:27 UTC, mfogel commented on real-main/app/models/user/manager.py
> +            user_id = user_ids_mapped_contact_ids[contact_id]
```suggestion
        for contact_id, user_id in user_ids_mapped_contact_ids.items():
```

2020-10-02 15:27 UTC, mfogel commented on real-main/app/models/user/manager.py
> +                email_contacts[email] = contact['contactId']
```suggestion
            email_contacts.update({email: contact['contactId'] for email in contact.get('emails, [])})
```

Same thing can be done for phone, of course.

2020-10-02 15:45 UTC, zkhin commented on real-main/app/models/user/manager.py
> +        }
Yes, I sorted to figure out the unit test

2020-10-02 16:05 UTC, zkhin commented on real-main/app/models/user/manager.py
> +        }
Can you suggest a better idea to figure out the spec without sorting in the backend?

2020-10-02 16:26 UTC, mfogel commented on real-main/app/models/user/manager.py
> +        }
I would actually consider changing the response format of `UserManager.find_contacts()` to just return a python dictionary of contact_id => user_id

In the handler in `app/handers/appsync/handlers.py` I would transform the response from `UserManager.find_contacts()` like so:

```py
contact_id_to_user_id = user_manager.find_contacts(...)
return [{'contactId': contact_id, 'userId': user_id} for contact_id, user_id in contact_id_to_user_id.items()]
```

Then I would set up a new pipeline graphql resolver for `FoundContact.user`. This basically just needs to do the same thing as the existing pipeline resolver for `Query.user` it just has to pull the user id from `ctx.source.userId`, rather than `ctx.args.userId`

The reason for this is that I see another place in this implementation that is currently doing `O(n)` queries which I had missed before. I'll point that out.

As far as I remember, none of our graphql resolver do `O(n)` queries yet. In general, good API design shouldn't require ever doing `O(n)` queries in any resolver, IMHO

2020-10-02 16:29 UTC, mfogel commented on real-main/app/models/user/manager.py
> +            found_contacts.append({'contactId': contact_id, 'user': self.get_user(user_id)})
`O(n)` queries here!

If you apply the changes I mentioned in https://github.com/real-social-media/backend/pull/72#discussion_r498913555 I think this will disappear.

2020-10-05 14:33 UTC, mfogel commented on real-main/mapping-templates/FoundContact.user/after.response.vtl
> +  #return
This `#return` right here is a problem, because in the GQL schema specifies this as non-null: `User!`. I should have foreseen this.

I can see two ways to fix this. One would be to move the pipeline resolver from `FoundContact.user` to `Query.foundContacts`. Another would be to change `FoundContact.user` so it can be null. The second one is slightly less performant but it should be easier to implement so let's go with it.

I'm going to suggest a series of changes to this PR to get there, coming soon.

2020-10-05 14:41 UTC, zkhin commented on real-main/mapping-templates/FoundContact.user/after.response.vtl
> +  #return
You mean this line should be changed to `user: User`, right?
https://github.com/real-social-media/backend/blob/29dca43c09dda50d41cd88d63ba7cccae036a366/real-main/schema.graphql#L936

2020-10-05 14:49 UTC, mfogel requested changes
Ok, so the main change here is that the response of `Query.findContacts()` should contain an entry for each `contactId` the client sends.

If the backend found the user, then `FoundContact.user` contains that user.
If the backend did not find the user (or the user was found, but is blocking the caller), then `FoundContact.user` is null.

The integration tests will need to be updated to match this change. (I didn't spec out exactly were they have to change, I haven't read them through closely yet).

Let me know if you have questions, thank you

2020-10-05 14:49 UTC, mfogel commented on real-main/schema.graphql
> +  user: User!
```suggestion
  user: User
```

Previously, `Query.findContacts()` only returned `FoundContact` for users that were found. The changes I suggest now will change this so that a `FoundContact` is always returned, however, `FoundContact.user` will be `null` if no user was found.

2020-10-05 14:49 UTC, mfogel commented on real-main/mapping-templates/FoundContact.user/after.response.vtl
> +  })
Let's just hide users that have blocked the caller completely here. Thus it will appear to the caller (the user that's been blocked) that the other user doesn't exist.

```suggestion
  #return
```

2020-10-05 14:49 UTC, mfogel commented on real-main/app/handlers/appsync/handlers.py
> +    return [{'contactId': contact_id, 'userId': user_id} for contact_id, user_id in contact_id_to_user_id.items()]
```suggestion
    contact_ids = [contact['contactId'] for contact in contacts]
    return [{'contactId': contact_id, 'userId': contact_id_to_user_id.get(contact_id)} for contact_id in contact_ids]
```

2020-10-05 14:49 UTC, mfogel commented on real-main/mapping-templates/FoundContact.user/before.request.vtl
> +$util.toJson([$ctx.source.userId])
```suggestion
#if ($util.isNull($ctx.source.userId))
  #return
#end
$util.toJson([$ctx.source.userId])
```

2020-10-06 01:01 UTC, mfogel reviewed
I added a few comments on the integration tests primarily.

I would add an integration test. One that check to make sure that users that have blocked the query are not returned by `Query.findContacts`. Here's one way to do that:
- two users, us and them
- verify we can find them using their email
- they block us
- verify we can no longer find them using their email

I haven't reviewed the python unit tests yet... I will do so tomorrow.

2020-10-06 18:55 UTC, mfogel requested changes
This is very close - just the one suggestion here and then also, because in the mapping template blocked users are handled differently there should be a test exercising that behavior.

I would add an integration test that goes like this:

- two users, us and them
- verify we can find them using their email
- they block us
- verify we can no longer find them using their email

2020-10-06 18:55 UTC, mfogel commented on real-main/app/handlers/appsync/handlers.py
> +    caller_user.update_last_found_contacts_at(now=pendulum.now('utc'))
Even though I don't know if these actually do throw a `UserException`, I think it's still better to wrap them in this try-catch block because they may be changed in the future to do so.

Also, `contacts` is no longer a kwarg (it's just a normal positional argument) so I wouldn't use the `contacts=contacts` syntax on it, I would just pass in `contacts`.

```suggestion
    try:
        contact_id_to_user_id = user_manager.find_contacts(caller_user, contacts)
        caller_user.update_last_found_contacts_at(now=pendulum.now('utc'))
    except UserException as err:
        raise ClientException(str(err)) from err
        
```

2020-10-07 10:56 UTC, mfogel commented on integration-testing/tests/find-contacts.test.js
> +    expect(findContacts[0].user.photo).toBeTruthy()
This line is failing for me when I run these tests. `user.photo` is `null`. I'm not sure why. Does it fail for you? All the other integration tests are passing.

Side note: This assertion on `user.photo` is useful - as demonstrated by the fact that it's failing. I'm not sure about all the assertions on `user.username`, in every test. I might do assertions on `user.username` in _one_ test (perhaps something like 'test extra user fields'). I might also add assertions on a handful of other fields in that test. But I wouldn't bother to do those extra assertions in every test.

2020-10-07 11:24 UTC, zkhin commented on integration-testing/tests/find-contacts.test.js
> +    expect(findContacts[0].user.photo).toBeTruthy()
Hmm... it's passing all the tests on my side...strange.
![image](https://user-images.githubusercontent.com/4212008/95324650-64ff8d80-08e3-11eb-9c11-b03e48a1d08c.png)

2020-10-07 11:57 UTC, mfogel commented on integration-testing/tests/find-contacts.test.js
> +    expect(findContacts[0].user.photo).toBeTruthy()
crazy. thank you - I will investigate on my side to figure out why my dev env is failing.

2020-10-07 12:55 UTC, mfogel commented on integration-testing/tests/find-contacts.test.js
> +    expect(findContacts[0].user.photo).toBeTruthy()
Ok, I figured out what's going on. I think this test will fail for you in your dev env: https://github.com/real-social-media/backend/blob/master/integration-testing/tests/users/create-user/placeholder-photo.test.js#L21. Can you verify that it fails for you?

There is an unfortunate coupling between the backend project and the `themes` project (which is used to hold some images & files used by the frontend). We have an unused feature where when a new user is created, the backend scans a directory in the `themes` project that is full of default profile pictures, and selects a random one, and sets that as the new user's profile picture. However, we only ever added one default profile picture to that directory... so there are much simpler implementations possible to accomplish that than what now exists. And that would avoid this awkward coupling.

The result is that the integration tests are currently set up to expect that directory full of default profile pictures to be empty. I think this test, on this line, assumes that directory is _not_ empty. And I suspect that directory in your dev environment is not empty.

As such - could we just change this from `user.photo` to something else? Like maybe `user.subscriptionLevel` or `user.signedUpAt` ? Those attributes don't run into this gotcha.

2020-10-07 18:41 UTC, merged